# @package algorithm

config:
  horizon: 200
  rollout_fragment_length: 100
  sgd_minibatch_size: 64
  train_batch_size: 512
  gamma: 0.995
  lambda: 0.95
  num_envs_per_worker: 1
  num_gpus: 0
  clip_param: 0.2
  kl_coeff: 1.0
  num_sgd_iter: 10
  lr: 0.0001
  use_gae: True
  vf_share_layers: False
  entropy_coeff: 0.0001